### ISSUE TITLE
 import selective_scan_cuda ImportError

### ISSUE THREAD

**Issue by sove45** [csguoh/MambaIR#3]
excuse me,I raised the error when importing this package
error lies:
/home/dhw/anaconda3/bin/conda run -n zIR2 --no-capture-output python /home/dhw/zjb_workspace/IR/realDenoising/test_real_denoising_sidd.py 
Traceback (most recent call last):
  File "/home/dhw/zjb_workspace/IR/realDenoising/test_real_denoising_sidd.py", line 8, in <module>
    from basicsr.models.archs.mambairunet_arch import MambaIRUNet
  File "/home/dhw/zjb_workspace/IR/basicsr/__init__.py", line 1, in <module>
    from .archs import *
  File "/home/dhw/zjb_workspace/IR/basicsr/archs/__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "/home/dhw/zjb_workspace/IR/basicsr/archs/__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "/home/dhw/anaconda3/envs/zIR2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dhw/zjb_workspace/IR/basicsr/archs/mambair_arch.py", line 11, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, selective_scan_ref
  File "/home/dhw/anaconda3/envs/zIR2/lib/python3.9/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/dhw/anaconda3/envs/zIR2/lib/python3.9/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 11, in <module>
    import selective_scan_cuda
ImportError: /home/dhw/anaconda3/envs/zIR2/lib/python3.9/site-packages/selective_scan_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
ERROR conda.cli.main_run:execute(124): `conda run python /home/dhw/zjb_workspace/IR/realDenoising/test_real_denoising_sidd.py` failed. (See above for error)

Process finished with exit code 1

**Comment by csguoh** [comment]
It seems the above error is caused by this python line `import selective_scan_cuda`. It may occur when you install incompatible `pytorch`, `causal_conv1d`, `mamba_ssm` versions. I would suggest checking the environment of the above python liarbry and try to install a compatible version to resolve the issue.
