### ISSUE TITLE
Duplicate GPU detected : rank 1 and rank 3 both on CUDA device a000

### ISSUE THREAD

**Issue by bryanbocao** [csguoh/MambaIR#39]
Tried
```
(mambair) brcao@dawn:/eData05/brcao/Repos/MambaIR$ python3 -m torch.distributed.launch --nproc_per_node=8 --master_port=1234 basicsr/train.py -opt options/train/train_MambaIR_SR_x2.yml --launcher pytorch
```
but got
```
...
    File "/eData05/brcao/Repos/MambaIR/basicsr/models/base_model.py", line 97, in model_to_device
    net = DistributedDataParallel(
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.18.6
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 4000
Traceback (most recent call last):
  File "basicsr/train.py", line 224, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 130, in train_pipeline
    model = build_model(opt)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/sr_model.py", line 23, in __init__
    self.net_g = self.model_to_device(self.net_g)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/base_model.py", line 97, in model_to_device
    net = DistributedDataParallel(
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
Traceback (most recent call last):
  File "basicsr/train.py", line 224, in <module>
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.18.6
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 0 and rank 2 both on CUDA device 4000
    train_pipeline(root_path)
  File "basicsr/train.py", line 130, in train_pipeline
    model = build_model(opt)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/sr_model.py", line 23, in __init__
    self.net_g = self.model_to_device(self.net_g)
  File "/eData05/brcao/Repos/MambaIR/basicsr/models/base_model.py", line 97, in model_to_device
    net = DistributedDataParallel(
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 795, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/brcao/.local/lib/python3.8/site-packages/torch/distributed/utils.py", line 265, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.18.6
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:
Duplicate GPU detected : rank 1 and rank 3 both on CUDA device a000
```

**Comment by telangmu123-good** [comment]
我遇到了同样的问题，请问您解决了吗

**Comment by bryanbocao** [comment]
> 我遇到了同样的问题，请问您解决了吗

Not yet :(
