### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by bryanbocao** [csguoh/MambaIR#43]
```
conda env create -f environment.yaml
```

Error message:
```
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/brcao/Apps/anaconda3/envs/mambair/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/brcao/Repos/MambaIR/condaenv.s5m233c1.requirements.txt']
Pip subprocess output:
Collecting absl-py==2.1.0 (from -r /home/brcao/Repos/MambaIR/condaenv.s5m233c1.requirements.txt (line 1))
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting packaging (from -r /home/brcao/Repos/MambaIR/condaenv.s5m233c1.requirements.txt (line 2))
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting cachetools==5.3.3 (from -r /home/brcao/Repos/MambaIR/condaenv.s5m233c1.requirements.txt (line 3))
  Using cached cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting causal-conv1d==1.0.0 (from -r /home/brcao/Repos/MambaIR/condaenv.s5m233c1.requirements.txt (line 4))
  Using cached causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1k4gt23r/causal-conv1d_6ed2c477f63c4bb9a2804cbf0afa89ac/setup.py", line 8, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by bryanbocao** [comment]
I tried
```
pip3 install --upgrade pip
pip3 install packaging
python -m pip install -U pip
```
but the problem still persists.

Eventually, I tried removing the ```mambair``` env and ran
```
conda install -c conda-forge packaging
```
then the problem seemed solved.

**Comment by MuhammadEmmadSiddiqui** [comment]
Thanks @bryanbocao, it really helped me in my case as well
