### ISSUE TITLE
KeyError: "No object named 'MambaIRModel' found in 'model' registry!"

### ISSUE THREAD

**Issue by xfcxing** [csguoh/MambaIR#49]
Hello,

I encountered an issue while using the `basicsr` module in your project. Specifically, when I call the `build_model(opt)` function, I receive the following error:

Traceback (most recent call last):
  File "/data1/fengchuang/MambaIR-main/basicsr/test.py", line 46, in <module>
    test_pipeline(root_path)
  File "/data1/fengchuang/MambaIR-main/basicsr/test.py", line 36, in test_pipeline
    model = build_model(opt)
  File "/data1/fengchuang/anaconda3/envs/mambair/lib/python3.9/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/data1/fengchuang/anaconda3/envs/mambair/lib/python3.9/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'MambaIRModel' found in 'model' registry!"

I checked the `opt` configuration and ensured that `model_type` is set to `MambaIRModel`. However, it seems that the model cannot be found in the registry.

Could you please advise on how to resolve this issue? Are there any additional steps needed to register the `MambaIRModel`?

Thank you for your help!

**Comment by zhaoyong-li** [comment]
maybe you need to run this command "python setup.py develop" before next operations.

**Comment by wjkbigface** [comment]
请问你解决了嘛

**Comment by csguoh** [comment]
Have you changed the file name of `mambair_model.py` and `mambair_arch.py`? The registry code scans the folder file name to obtain the registried model. 
If you have not change the file name, you may give it a shot to remove the `basicsr` library in your conda environment since all the needed basicsr backends have already exist in the project file './baiscsr'. And you can also find in the `./environment.yaml` that basicsr is not installed.

**Comment by wjkbigface** [comment]
重新装了一下低torch版本就解决啦，谢谢！

**Comment by brooze-1** [comment]
![image](https://github.com/user-attachments/assets/4206a287-ead7-4a3e-8d77-56115ca8a9c0)
don't install baiscsr and modify the /MambaIR/basicsr/test.py can work it out!
