### ISSUE TITLE
 KeyError: "No object named 'MambaIRModel' found in 'model' registry!"

### ISSUE THREAD

**Issue by wjkbigface** [csguoh/MambaIR#53]
Name MambaIRModel is not found, use name: MambaIRModel_basicsr!
Traceback (most recent call last):
  File "/root/autodl-tmp/MambaIR-main/basicsr/train.py", line 225, in <module>
    train_pipeline(root_path)
  File "/root/autodl-tmp/MambaIR-main/basicsr/train.py", line 131, in train_pipeline
    model = build_model(opt)
  File "/root/miniconda3/envs/mambair/lib/python3.10/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/root/miniconda3/envs/mambair/lib/python3.10/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'MambaIRModel' found in 'model' registry!"

**Comment by liziang297** [comment]
excuse me，have you resolved the problem？

**Comment by csguoh** [comment]
Hi, you may refer to [this issue](https://github.com/csguoh/MambaIR/issues/49). Sorry for the late reply.
