### ISSUE TITLE
CUDA_out_of memory

### ISSUE THREAD

**Issue by formerlya** [csguoh/MambaIR#68]
2024-10-26 18:21:27,613 INFO: Validation ValSet,		 # psnr: 27.0127
2024-10-26 18:33:53,703 INFO: [Mamba..][epoch:  0, iter: 201,000, lr:(1.441e-05,)] [eta: 17:27:00, time (data): 0.732 (0.016)] l_pix: 4.2320e-02 
2024-10-26 18:46:17,277 INFO: [Mamba..][epoch:  0, iter: 202,000, lr:(1.419e-05,)] [eta: 17:17:18, time (data): 0.732 (0.010)] l_pix: 2.0193e-02 
2024-10-26 18:58:40,552 INFO: [Mamba..][epoch:  0, iter: 203,000, lr:(1.397e-05,)] [eta: 17:07:35, time (data): 0.771 (0.014)] l_pix: 2.4256e-02 
2024-10-26 19:11:04,947 INFO: [Mamba..][epoch:  0, iter: 204,000, lr:(1.375e-05,)] [eta: 16:57:50, time (data): 0.732 (0.010)] l_pix: 5.1429e-02 
2024-10-26 19:11:04,948 INFO: Saving models and training states.
Traceback (most recent call last):
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/train.py", line 326, in <module>
    main()
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/train.py", line 280, in main
    model.optimize_parameters(current_iter)
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/models/image_restoration_model.py", line 151, in optimize_parameters
    preds = self.net_g(self.lq)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/models/archs/mambairunet_arch.py", line 635, in forward
    out_dec_level1 = layer(out_dec_level1, [H, W])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/models/archs/mambairunet_arch.py", line 414, in forward
    x = input*self.skip_scale + self.drop_path(self.self_attention(x))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/models/archs/mambairunet_arch.py", line 376, in forward
    y1, y2, y3, y4 = self.forward_core(x)
  File "/ghome/code/MambaIR-main/realDenoising/basicsr/models/archs/mambairunet_arch.py", line 340, in forward_core
    xs = torch.cat([x_hwwh, torch.flip(x_hwwh, dims=[-1])], dim=1) # (1, 4, 192, 3136)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 144.00 MiB. GPU 1 has a total capacity of 10.75 GiB of which 137.56 MiB is free. Process 25604 has 10.61 GiB memory in use. Of the allocated memory 10.15 GiB is allocated by PyTorch, and 178.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I use batch_size=1,and add torch.cuda.empty_cache()
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

**Comment by csguoh** [comment]
Hi, you may reduce the input size during training by modify the yaml file in the ./options file fold, or use the gradient checkpointing tricks to reduce the GPU memory.
